version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: felix
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: themis_api_development
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "5173:80"
    environment:
      VITE_API_URL: http://api:3000
    depends_on:
      - api

volumes:
  db_data: